app_service_encode_passwords:
    pattern:  /service/encodePasswords
    defaults: { _controller: D4DAppBundle:AppService:encodePasswords }
    
app_service_check_login:
    pattern:  /service/checkLogin
    defaults: { _controller: D4DAppBundle:AppService:checkLogin }    

app_service_override_passwords:
    pattern:  /service/overridePasswords
    defaults: { _controller: D4DAppBundle:AppService:overridePasswords }
    
user_home:
    path:     /home
    defaults: { _controller: D4DAppBundle:Common\Security:secured }
    
user_login:
    path:     /login
    defaults: { _controller: D4DAppBundle:Common\Security:userLogin }
    
user_login_check:
    path: /login_check 
    
user_logout:
    path: /logout 
    


admin_home:   
    path:     /admin/users/statistics
    defaults: { _controller: D4DAppBundle:Backend\Users:statistics }
    
admin_login:
    path:     /admin/login
    defaults: { _controller: D4DAppBundle:Common\Security:adminLogin }
    
admin_login_check:
    path: /admin/login_check 

admin_logout:
    path: /admin/logout
    

admin_users_statistics:   
    path:     /admin/users/statistics/{value}
    defaults: { _controller: D4DAppBundle:Backend\Users:statistics, value:1 }        

admin_faq:
  path:     /admin/faq
  defaults: { _controller: D4DAppBundle:Backend\Faq:index }
  
admin_faq_edit:   
    path:     /admin/faq/edit/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\Faq:formFaq, id:0 page:1 }
    
admin_faq_add:   
    path:     /admin/faq/add
    defaults: { _controller: D4DAppBundle:Backend\Faq:formFaq }
    
admin_faq_delete:   
    path:     /admin/faq/delete/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\Faq:deleteFaq, id:0 page:1 }
    
admin_faq_category_edit:   
    path:     /admin/faq/category/edit/{id}
    defaults: { _controller: D4DAppBundle:Backend\Faq:formCategoty, id:0 }
    
admin_faq_category_add:   
    path:     /admin/faq/category/add
    defaults: { _controller: D4DAppBundle:Backend\Faq:formCategoty }
    
admin_faq_category_delete:   
    path:     /admin/faq/category/delete/{id}
    defaults: { _controller: D4DAppBundle:Backend\Faq:deleteCategory, id:0 }