app_service_encode_passwords:
    pattern:  /service/encodePasswords
    defaults: { _controller: D4DAppBundle:AppService:encodePasswords }
    
app_service_check_login:
    pattern:  /service/checkLogin
    defaults: { _controller: D4DAppBundle:AppService:checkLogin }    

app_service_override_passwords:
    pattern:  /service/overridePasswords
    defaults: { _controller: D4DAppBundle:AppService:overridePasswords }


    
user_home:
    path:     /home
    defaults: { _controller: D4DAppBundle:Common\Security:secured }
    
user_login:
    path:     /login
    defaults: { _controller: D4DAppBundle:Common\Security:userLogin }
    
user_login_check:
    path: /login_check 
    
user_logout:
    path: /logout 
    



admin_home:   
    path:     /admin/users/statistics/{filter}
    defaults: { _controller: D4DAppBundle:Backend\Users:statistics, filter:total} 
    
admin_login:
    path:     /admin/login
    defaults: { _controller: D4DAppBundle:Common\Security:adminLogin }
    
admin_login_check:
    path: /admin/login_check 

admin_logout:
    path: /admin/logout
    

 
            
admin_users_statistics_action:   
    path:     /admin/users/statistics/{filter}/{action}
    defaults: { _controller: D4DAppBundle:Backend\Users:actions, filter:total, action:false }
    
admin_users_profile:   
    path:     /admin/users/profile/{userId}
    defaults: { _controller: D4DAppBundle:Backend\Users:profile, userId:0 }
    
admin_users_search:   
    path:     /admin/users/search
    defaults: { _controller: D4DAppBundle:Backend\Users:search}        




admin_faq:
  path:     /admin/faq
  defaults: { _controller: D4DAppBundle:Backend\Faq:index }
  
admin_faq_edit:   
    path:     /admin/faq/edit/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\Faq:formFaq, id:0, page:1 }
    
admin_faq_add:   
    path:     /admin/faq/add
    defaults: { _controller: D4DAppBundle:Backend\Faq:formFaq }
    
admin_faq_delete:   
    path:     /admin/faq/delete/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\Faq:deleteFaq, id:0, page:1 }
    
admin_faq_category_edit:   
    path:     /admin/faq/category/edit/{id}
    defaults: { _controller: D4DAppBundle:Backend\Faq:formCategoty, id:0 }
    
admin_faq_category_add:   
    path:     /admin/faq/category/add
    defaults: { _controller: D4DAppBundle:Backend\Faq:formCategoty }
    
admin_faq_category_delete:   
    path:     /admin/faq/category/delete/{id}
    defaults: { _controller: D4DAppBundle:Backend\Faq:deleteCategory, id:0 }




admin_news:
  path:     /admin/news
  defaults: { _controller: D4DAppBundle:Backend\News:index }
  
admin_news_edit:   
    path:     /admin/news/edit/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\News:formNews, id:0, page:1 }
    
admin_news_add:   
    path:     /admin/news/add
    defaults: { _controller: D4DAppBundle:Backend\News:formNews }
    
admin_news_delete:   
    path:     /admin/news/delete/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\News:deleteNews, id:0, page:1 }



   
admin_pages:
  path:     /admin/pages
  defaults: { _controller: D4DAppBundle:Backend\Page:index }
  
admin_pages_edit:   
    path:     /admin/pages/edit/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\Page:formPage, id:0, page:1 }
    
admin_pages_add:   
    path:     /admin/pages/add
    defaults: { _controller: D4DAppBundle:Backend\Page:formPage }
    
admin_pages_delete:   
    path:     /admin/pages/delete/{id}/{page}
    defaults: { _controller: D4DAppBundle:Backend\Page:deletePage, id:0, page:1 }
