D4D\AppBundle\Entity\Faq:
  properties:
    faqq:
      - NotBlank:
            message: "Field Question is empty" 
      - Length:
            min: 4
            minMessage: "Error min 4 letters"       
    faqa:
      - NotBlank:
            message: "Field Answer is empty"  
            
D4D\AppBundle\Entity\Faqcategory:
  properties:
    faqcategoryname:
      - NotBlank:
            message: "Field Category is empty"
#      - Length:
#            min: 4
#            minMessage: "Field Category is empty"    
            
D4D\AppBundle\Entity\News:
  properties:    
    newsitemsubject:
      - NotBlank:
            message: "Field Subject is empty"
    newsitembody:
      - NotBlank:
            message: "Field Body is empty"
      - Length:
            min: 4
            minMessage: "Min 4 letters in field Body" 

                        
D4D\AppBundle\Entity\LangDyncpages:
  properties:
    pagename:
      - NotBlank:
          message: "Field Name is empty"
#    pagetitle:
#      - NotBlank:
#          message: "Field Title is empty"
    pagebody:
      - NotBlank:
            message: "Field Body is empty"
      - Length:
            min: 4
            minMessage: "Min 4 letters in field Body"   

D4D\AppBundle\Entity\Banners:
  properties:
    bannerfileext:
      - File:
            maxSize: 512k
            mimeTypes: [image/jpeg, image/jpg, image/gif, application/x-shockwave-flash]
            mimeTypesMessage: Please upload a valid file (gif, jpg, swf)
            
D4D\AppBundle\Entity\Users:
  properties:
    useremail:
      - Email:
            message: The email "{{ value }}" is not a valid email.
            checkMX: true
    userpass:
      - Length:
            min: 4
            minMessage: "Min 4 letters in Password"
            max: 12
            maxMessage: "Min 12 letters in Password"
    usernic:
    usergender:
    userfname:
    userlname:
    userbirthday:
    countrycode:
      - NotEqualTo:
            value: --
            message: "Please select country"
    cityname:
    countryoforigincode:
      - NotEqualTo:
            value: --
            message: "Please select country"