security:    
    encoders:
        D4D\AppBundle\Entity\Users: sha512    

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]        
        
    providers:        
        user_db:
            entity: { class: D4DAppBundle:Users, property: usernic }    

    firewalls:
        
        admin_area:
            context: my_context            
            pattern:   ^/admin
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: admin_home                 
            logout:
                path:   /admin/logout
                target: /admin/login
        
        user_area:
            context: my_context            
            pattern:   ^/user
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_home
            logout:
                path:   /user/logout
                target: /user/login
                
        forum_area:
            context: my_context            
            pattern:   ^/forum
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: ccdn_homepage
            logout:
                path:   /user/logout
                target: /user/login
                
    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forum, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/home, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }        