D4D\AppBundle\Entity\Adminproperties:
    type: entity
    table: adminProperties
    uniqueConstraints:
        UQ_adminProperties_propName:
            columns:
                - propName
    id:
        propid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: propId
            generator:
                strategy: IDENTITY
    fields:
        propvalue:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: propValue
        propname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: propName
        propdesc:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: propDesc
        propdisplaytype:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: propDisplayType
        propvalueslist:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: propValuesList
        propappname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: propAppName
        changeable:
            type: boolean
            nullable: true
            default: '0'
        propgroup:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: propGroup
    lifecycleCallbacks: {  }
