D4D\AppBundle\Entity\Haircolor:
    type: entity
    table: hairColor
    uniqueConstraints:
        IX_hairColor:
            columns:
                - hairColorName
    id:
        haircolorid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: hairColorId
            generator:
                strategy: IDENTITY
    fields:
        haircolorname:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: hairColorName
    lifecycleCallbacks: {  }
