D4D\AppBundle\Entity\LocRegions:
    type: entity
    table: loc_regions
    id:
        countrycode:
            type: string
            nullable: false
            length: 2
            fixed: false
            id: true
            column: countryCode
        regioncode:
            type: string
            nullable: false
            length: 2
            fixed: false
            id: true
            column: regionCode
    fields:
        regionname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: regionName
    lifecycleCallbacks: {  }
