D4D\AppBundle\Entity\Blogcategory:
    type: entity
    table: blogCategory
    id:
        blogcategoryid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: blogCategoryId
            generator:
                strategy: IDENTITY
    fields:
        blogcategoryname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: blogCategoryName
    lifecycleCallbacks: {  }
