D4D\AppBundle\Entity\ForumForums:
    type: entity
    table: forum_forums
    id:
        forumid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: forumId
            generator:
                strategy: IDENTITY
    fields:
        forumname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: forumName
        forumdesc:
            type: string
            nullable: true
            length: 4000
            fixed: false
            column: forumDesc
        forumorderby:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: forumOrderBy
    lifecycleCallbacks: {  }
