D4D\AppBundle\Entity\Hairlength:
    type: entity
    table: hairLength
    uniqueConstraints:
        IX_hairLength:
            columns:
                - hairLengthName
    id:
        hairlengthid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: hairLengthId
            generator:
                strategy: IDENTITY
    fields:
        hairlengthname:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: hairLengthName
    lifecycleCallbacks: {  }
