D4D\AppBundle\Entity\LangLanguages:
    type: entity
    table: lang_languages
    id:
        langid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: langId
            generator:
                strategy: IDENTITY
    fields:
        langnameenglish:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: langNameEnglish
        langnamenative:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: langNameNative
        langcodepage:
            type: string
            nullable: true
            length: 4
            fixed: false
            column: langCodepage
        langcode:
            type: string
            nullable: true
            length: 2
            fixed: false
            column: langCode
        langdir:
            type: string
            nullable: true
            length: 3
            fixed: false
            default: ltr
            column: langDir
        langstatus:
            type: integer
            nullable: false
            unsigned: false
            default: '-1'
            column: langStatus
        langdefault:
            type: boolean
            nullable: true
            default: '0'
            column: langDefault
    manyToMany:
        pageid:
            targetEntity: LangDyncpages
            cascade: {  }
            mappedBy: langid
            inversedBy: null
            joinTable: null
            orderBy: null
        langErrorid:
            targetEntity: LangErrors
            cascade: {  }
            mappedBy: langid
            inversedBy: null
            joinTable: null
            orderBy: null
        langStringid:
            targetEntity: LangStrings
            cascade: {  }
            mappedBy: langid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
