D4D\AppBundle\Entity\LocCities:
    type: entity
    table: loc_cities
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        countrycode:
            type: string
            nullable: false
            length: 2
            fixed: false
            column: countryCode
        regioncode:
            type: string
            nullable: true
            length: 2
            fixed: false
            column: regionCode
        cityname:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: cityName
        latitude:
            type: float
            nullable: true
            precision: 53
            scale: 0
        longitude:
            type: float
            nullable: true
            precision: 53
            scale: 0
        zipcode:
            type: string
            nullable: true
            length: 5
            fixed: false
            column: zipCode
    lifecycleCallbacks: {  }
