D4D\AppBundle\Entity\Maritalstatus:
    type: entity
    table: maritalStatus
    uniqueConstraints:
        IX_maritalStatus:
            columns:
                - maritalStatusName
    id:
        maritalstatusid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: maritalStatusId
            generator:
                strategy: IDENTITY
    fields:
        maritalstatusname:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: maritalStatusName
    lifecycleCallbacks: {  }
