Adminsavedreports:
    type: entity
    table: adminSavedReports
    id:
        savedreportid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: savedReportId
            generator:
                strategy: IDENTITY
    fields:
        savedreportname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: savedReportName
        savedreportlink:
            type: string
            nullable: true
            length: 2048
            fixed: false
            column: savedReportLink
        isstats:
            type: boolean
            nullable: true
            default: '0'
            column: isStats
        ishomepage:
            type: boolean
            nullable: true
            default: '0'
            column: isHomePage
    lifecycleCallbacks: {  }
