Eyescolor:
    type: entity
    table: eyesColor
    uniqueConstraints:
        IX_eyesColor:
            columns:
                - eyesColorName
    id:
        eyescolorid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: eyesColorId
            generator:
                strategy: IDENTITY
    fields:
        eyescolorname:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: eyesColorName
    lifecycleCallbacks: {  }
