Globalblacklist:
    type: entity
    table: globalBlackList
    id:
        useremail:
            type: string
            nullable: false
            length: 100
            fixed: false
            id: true
            column: userEmail
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
