LangDbvalues:
    type: entity
    table: lang_dbValues
    indexes:
        IDX_70F9322E97A33CE7:
            columns:
                - langId
    id:
        tablename:
            type: string
            nullable: false
            length: 255
            fixed: false
            id: true
            column: tableName
        valueid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: valueId
    fields:
        valuename:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: valueName
    oneToOne:
        langid:
            targetEntity: LangLanguages
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                langId:
                    referencedColumnName: langId
            orphanRemoval: false
    lifecycleCallbacks: {  }
