LocCountries:
    type: entity
    table: loc_countries
    id:
        countrycode:
            type: string
            nullable: false
            length: 2
            fixed: false
            id: true
            column: countryCode
            generator:
                strategy: IDENTITY
    fields:
        countryname:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: countryName
    lifecycleCallbacks: {  }
