Occupation:
    type: entity
    table: occupation
    uniqueConstraints:
        IX_occupation:
            columns:
                - occupationName
    id:
        occupationid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: occupationId
            generator:
                strategy: IDENTITY
    fields:
        occupationname:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: occupationName
    lifecycleCallbacks: {  }
