Userdevices:
    type: entity
    table: userDevices
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: true
            unsigned: false
            column: userId
        gcmdeviceid:
            type: text
            nullable: true
            length: -1
            fixed: false
            column: gcmDeviceId
        apndeviceid:
            type: string
            nullable: true
            length: 0
            fixed: false
            column: apnDeviceId
    lifecycleCallbacks: {  }
